### ISSUE TITLE
dry-logic 0.4.0 breaking dry-types 0.8.1

### ISSUE THREAD

**Issue by bolek** [dry-rb/dry-types#149]
It seems that `dry-logic` 0.4.0 is breaking `dry-types` 0.8.1.

I am getting the following error in one of my apps after upgrading to dry-logic 0.4.0

```
dry-types-0.8.1/lib/dry/types/constraints.rb:8:in `curry': no implicit conversion of Class into Integer (TypeError)
  from dry-types-0.8.1/lib/dry/types/constraints.rb:8:in `block in Rule'
  from dry-types-0.8.1/lib/dry/types/constraints.rb:8:in `each'
  from dry-types-0.8.1/lib/dry/types/constraints.rb:8:in `map'
  from dry-types-0.8.1/lib/dry/types/constraints.rb:8:in `Rule'
  from dry-types-0.8.1/lib/dry/types/builder.rb:22:in `constrained'
  from dry-types-0.8.1/lib/dry/types/core.rb:32:in `block in <module:Types>'
  from dry-types-0.8.1/lib/dry/types/core.rb:31:in `each'
  from dry-types-0.8.1/lib/dry/types/core.rb:31:in `<module:Types>'
  from dry-types-0.8.1/lib/dry/types/core.rb:2:in `<module:Dry>'
  from dry-types-0.8.1/lib/dry/types/core.rb:1:in `<top (required)>'
  from dry-types-0.8.1/lib/dry/types.rb:104:in `require'
  from dry-types-0.8.1/lib/dry/types.rb:104:in `<top (required)>'
  from dry-types-0.8.1/lib/dry-types.rb:1:in `require'
  from dry-types-0.8.1/lib/dry-types.rb:1:in `<top (required)>'
```

**Comment by ramanbuttar** [comment]
Seeing the same trying to install https://github.com/accessd/rails-settings-ui

**Comment by solnic** [comment]
Pushing new releases later today. Sorry about that

**Comment by solnic** [comment]
You can pin dry-logic to `0.3.0` to fix this btw.

**Comment by solnic** [comment]
New gems have been released so I'm closing this one
