### ISSUE TITLE
dry/types/decorator.rb:74:in `method_missing': undefined method `failure' for #<Dry::Types::Safe> (NoMethodError)

### ISSUE THREAD

**Issue by joevandyk** [dry-rb/dry-types#184]
```
require 'dry-struct'

module Types
  include Dry::Types.module
end

class Contact < Dry::Struct
  constructor_type :symbolized
  attribute :age, Types::Coercible::Int.optional
end

Contact.new("age" => "2.2")
```

results in

```
/Users/joe/.gem/ruby/2.3.3/gems/dry-types-0.9.4/lib/dry/types/decorator.rb:74:in `method_missing': undefined method `failure' for #<Dry::Types::Safe:0x007f969b85ef10> (NoMethodError)
Did you mean?  fail
	from /Users/joe/.gem/ruby/2.3.3/gems/dry-types-0.9.4/lib/dry/types/safe.rb:31:in `rescue in try'
	from /Users/joe/.gem/ruby/2.3.3/gems/dry-types-0.9.4/lib/dry/types/safe.rb:29:in `try'
	from /Users/joe/.gem/ruby/2.3.3/gems/dry-types-0.9.4/lib/dry/types/safe.rb:13:in `call'
	from /Users/joe/.gem/ruby/2.3.3/gems/dry-types-0.9.4/lib/dry/types/hash/schema.rb:75:in `block in coerce'
	from /Users/joe/.gem/ruby/2.3.3/gems/dry-types-0.9.4/lib/dry/types/hash/schema.rb:217:in `block in resolve'
	from /Users/joe/.gem/ruby/2.3.3/gems/dry-types-0.9.4/lib/dry/types/hash/schema.rb:208:in `each'
	from /Users/joe/.gem/ruby/2.3.3/gems/dry-types-0.9.4/lib/dry/types/hash/schema.rb:208:in `resolve'
	from /Users/joe/.gem/ruby/2.3.3/gems/dry-types-0.9.4/lib/dry/types/hash/schema.rb:73:in `coerce'
	from /Users/joe/.gem/ruby/2.3.3/gems/dry-types-0.9.4/lib/dry/types/hash/schema.rb:27:in `call'
	from /Users/joe/.gem/ruby/2.3.3/gems/dry-types-0.9.4/lib/dry/types/constructor.rb:39:in `call'
	from /Users/joe/.gem/ruby/2.3.3/gems/dry-struct-0.2.1/lib/dry/struct/class_interface.rb:77:in `new'
	from /private/tmp/dry.rb:12:in `<main>'
```

**Comment by solnic** [comment]
Is this still a problem?

**Comment by joevandyk** [comment]
Yes.

```
$ cat /tmp/t.rb
require 'dry-struct'

module Types
  include Dry::Types.module
end

class Contact < Dry::Struct
  constructor_type :symbolized
  attribute :age, Types::Coercible::Int.optional
end

Contact.new("age" => "2.2")
```

```
$ ruby /tmp/t.rb
/Users/joe/.gem/ruby/2.3.3/gems/dry-types-0.11.0/lib/dry/types/decorator.rb:75:in `method_missing': undefined method `failure' for #<Dry::Types::Safe:0x007f8bc42792d0> (NoMethodError)
Did you mean?  fail
	from /Users/joe/.gem/ruby/2.3.3/gems/dry-types-0.11.0/lib/dry/types/safe.rb:32:in `rescue in try'
	from /Users/joe/.gem/ruby/2.3.3/gems/dry-types-0.11.0/lib/dry/types/safe.rb:30:in `try'
	from /Users/joe/.gem/ruby/2.3.3/gems/dry-types-0.11.0/lib/dry/types/safe.rb:14:in `call'
	from /Users/joe/.gem/ruby/2.3.3/gems/dry-types-0.11.0/lib/dry/types/hash/schema.rb:91:in `block in coerce'
	from /Users/joe/.gem/ruby/2.3.3/gems/dry-types-0.11.0/lib/dry/types/hash/schema.rb:260:in `block in resolve'
	from /Users/joe/.gem/ruby/2.3.3/gems/dry-types-0.11.0/lib/dry/types/hash/schema.rb:251:in `each'
	from /Users/joe/.gem/ruby/2.3.3/gems/dry-types-0.11.0/lib/dry/types/hash/schema.rb:251:in `resolve'
	from /Users/joe/.gem/ruby/2.3.3/gems/dry-types-0.11.0/lib/dry/types/hash/schema.rb:89:in `coerce'
	from /Users/joe/.gem/ruby/2.3.3/gems/dry-types-0.11.0/lib/dry/types/hash/schema.rb:27:in `call'
	from /Users/joe/.gem/ruby/2.3.3/gems/dry-types-0.11.0/lib/dry/types/constructor.rb:39:in `call'
	from /Users/joe/.gem/ruby/2.3.3/gems/dry-struct-0.3.1/lib/dry/struct/class_interface.rb:91:in `new'
	from /tmp/t.rb:12:in `<main>'
```

**Comment by pablocrivella** [comment]
Similar issue here:

```ruby
require 'dry-struct'

module Types
  include Dry::Types.module
end

class Contact < Dry::Struct
  constructor_type :symbolized
  attribute :admin, Types::Bool.default(false)
end

Contact.new(admin: true) # =>

# NoMethodError: undefined method `success' for #<Dry::Types::Default:0x007fac520c4e40>
# from /Users/pablocrivella/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/dry-types-0.11.1/lib/dry/types/decorator.rb:75:in `method_missing'
```

**Comment by GustavoCaso** [comment]
Is anyone working on this one? If not I would like take this

**Comment by timriley** [comment]
@GustavoCaso pretty sure it's there for the taking :)

**Comment by solnic** [comment]
FWIW, it's not recommended to use symbolized constructor types for structs, something else should pre-process the data before passing them to struct constructors.

**Comment by GustavoCaso** [comment]
I have done some checks and the example:

```ruby
require 'dry-struct'

module Types
  include Dry::Types.module
end

class Contact < Dry::Struct
  constructor_type :symbolized
  attribute :age, Types::Coercible::Int.optional
end

Contact.new("age" => "2.2")
```

Does fail with dry-types in the latest release but with `master` branch doesn't

**Comment by solnic** [comment]
This was fixed via https://github.com/dry-rb/dry-types/commit/795b412d0712a23d49e114d831c67b3b87a5ae73
