### ISSUE TITLE
0.15 breaks dry-validation

### ISSUE THREAD

**Issue by mensfeld** [dry-rb/dry-types#307]
This is what I see after upgrading dry-types with `dry-validation (0.13.0)`

```
NoMethodError: undefined method `merge' for :weak:Symbol
  /gems/2.6.0/gems/dry-types-0.15.0/lib/dry/types/compiler.rb:64:in `visit_hash'
  /gems/2.6.0/gems/dry-types-0.15.0/lib/dry/types/compiler.rb:16:in `visit'
  /gems/2.6.0/gems/dry-types-0.15.0/lib/dry/types/compiler.rb:11:in `call'
  /gems/2.6.0/gems/dry-validation-0.13.0/lib/dry/validation/input_processor_compiler.rb:16:in `call'
  /gems/2.6.0/gems/dry-validation-0.13.0/lib/dry/validation/schema/deprecated.rb:14:in `input_processor'
  /gems/2.6.0/gems/dry-validation-0.13.0/lib/dry/validation/schema/class_interface.rb:169:in `default_options'
  /gems/2.6.0/gems/dry-validation-0.13.0/lib/dry/validation/schema/class_interface.rb:39:in `new'
  /gems/2.6.0/gems/dry-validation-0.13.0/lib/dry/validation.rb:23:in `Schema'
  /home/mencio/Software/Coditsu/Engines/OffendingEngine/lib/offending_engine/schemas/snippet.rb:6:in `<module:Schemas>'
  /home/mencio/Software/Coditsu/Engines/OffendingEngine/lib/offending_engine/schemas/snippet.rb:4:in `<module:OffendingEngine>'
  /home/mencio/Software/Coditsu/Engines/OffendingEngine/lib/offending_engine/schemas/snippet.rb:3:in `<top (required)>'
  /gems/2.6.0/gems/require_all-2.0.0/lib/require_all.rb:208:in `require'
  /gems/2.6.0/gems/require_all-2.0.0/lib/require_all.rb:208:in `__require'
  /gems/2.6.0/gems/require_all-2.0.0/lib/require_all.rb:98:in `block in require_all'
  /gems/2.6.0/gems/require_all-2.0.0/lib/require_all.rb:96:in `each'
  /gems/2.6.0/gems/require_all-2.0.0/lib/require_all.rb:96:in `require_all'
  /home/mencio/Software/Coditsu/Engines/OffendingEngine/lib/offending_engine.rb:93:in `block in <top (required)>'
  /home/mencio/Software/Coditsu/Engines/OffendingEngine/lib/offending_engine.rb:93:in `each'
  /home/mencio/Software/Coditsu/Engines/OffendingEngine/lib/offending_engine.rb:93:in `<top (required)>'
  /2.6.0/irb/init.rb:278:in `require'
  /2.6.0/irb/init.rb:278:in `block in load_modules'
  /2.6.0/irb/init.rb:276:in `each'
  /2.6.0/irb/init.rb:276:in `load_modules'
  /2.6.0/irb/init.rb:21:in `setup'
  /2.6.0/irb.rb:376:in `start'
  /gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
  /home/mencio/.rbenv/versions/2.6.2/bin/irb:23:in `load'
  /home/mencio/.rbenv/versions/2.6.2/bin/irb:23:in `<top (required)>'

```

**Comment by flash-gordon** [comment]
Yes, this is mentioned in the changelog. dry-validation 0.13 isn't compatible with dry-types 0.15 and will never be. I'll push 0.13.1 shortly which will stick dry-t to 0.14.

**Comment by flash-gordon** [comment]
https://rubygems.org/gems/dry-validation/versions/0.13.1
