### ISSUE TITLE
`Types.Array(SomeType)` raises non-dry errors

### ISSUE THREAD

**Issue by twe4ked** [dry-rb/dry-types#311]
```ruby
require 'dry/types'
require 'dry/struct'

module Types
  include Dry::Types.module

  LocalizedText = Types::Hash.schema(
    text: Types::Strict::String,
    locale: Types::Strict::String,
  )
  LocalizedTextArray = Types.Array(LocalizedText)
end

class X < Dry::Struct
  attribute :name, Types::LocalizedTextArray
end

X.new(name: nil)
```

Raises the following error, I would expect a `Dry::Types::ConstraintError`, `Dry::Types::SchemaError`, or `Dry::Struct::Error` error.

```
Traceback (most recent call last):
        9: from test.rb:18:in `<main>'
        8: from /Users/odin/.gem/ruby/2.6.2/gems/dry-struct-0.6.0/lib/dry/struct/class_interface.rb:225:in `new'
        7: from /Users/odin/.gem/ruby/2.6.2/gems/dry-types-0.14.0/lib/dry/types/constructor.rb:53:in `call'
        6: from /Users/odin/.gem/ruby/2.6.2/gems/dry-types-0.14.0/lib/dry/types/hash/schema.rb:42:in `call'
        5: from /Users/odin/.gem/ruby/2.6.2/gems/dry-types-0.14.0/lib/dry/types/hash/schema.rb:186:in `coerce'
        4: from /Users/odin/.gem/ruby/2.6.2/gems/dry-types-0.14.0/lib/dry/types/hash/schema.rb:140:in `resolve'
        3: from /Users/odin/.gem/ruby/2.6.2/gems/dry-types-0.14.0/lib/dry/types/hash/schema.rb:140:in `each'
        2: from /Users/odin/.gem/ruby/2.6.2/gems/dry-types-0.14.0/lib/dry/types/hash/schema.rb:144:in `block in resolve'
        1: from /Users/odin/.gem/ruby/2.6.2/gems/dry-types-0.14.0/lib/dry/types/hash/schema.rb:188:in `block in coerce'
/Users/odin/.gem/ruby/2.6.2/gems/dry-types-0.14.0/lib/dry/types/array/member.rb:20:in `call': undefined method `map' for nil:NilClass (NoMethodError)
```

Also, interestingly:

```ruby
X.new(name: {})
```

Doesn't raise an error.

I get expected errors with:

```ruby
X.new(name: [{text: 1, locale: 1}])
```

Is this expected behaviour?

<details>
<summary><code>$ grep dry Gemfile.lock</code></summary>
```
    dry-configurable (0.8.2)
      dry-core (~> 0.4, >= 0.4.7)
    dry-container (0.7.0)
      dry-configurable (~> 0.1, >= 0.1.3)
    dry-core (0.4.7)
    dry-equalizer (0.2.1)
    dry-inflector (0.1.2)
    dry-logic (0.5.0)
      dry-container (~> 0.2, >= 0.2.6)
      dry-core (~> 0.2)
      dry-equalizer (~> 0.2)
    dry-struct (0.6.0)
      dry-core (~> 0.4, >= 0.4.3)
      dry-equalizer (~> 0.2)
      dry-types (~> 0.13)
    dry-types (0.14.0)
      dry-container (~> 0.3)
      dry-core (~> 0.4, >= 0.4.4)
      dry-equalizer (~> 0.2)
      dry-inflector (~> 0.1, >= 0.1.2)
      dry-logic (~> 0.5, >= 0.5)
    dry-validation (0.13.0)
      dry-configurable (~> 0.1, >= 0.1.3)
      dry-core (~> 0.2, >= 0.2.1)
      dry-equalizer (~> 0.2)
      dry-logic (~> 0.5, >= 0.5.0)
      dry-types (~> 0.14, >= 0.14)
```
</details>

**Comment by flash-gordon** [comment]
This is going to be fixed in the next version but I'll keep this issue open for now to ensure we have it covered.

**Comment by twe4ked** [comment]
Awesome! Thanks for the prompt reply. The issue is helpful for me too because it’s in a code comment :)

**Comment by flash-gordon** [comment]
This is all addressed in master but you'll need to use strict types if you want to have an error on `X.new(name: nil)` or `X.new(name: {})`. For backward compatibility reasons `include Dry::Types.module` will import nominal types in the new version but if you change it to `include Dry.Types()` it'll do exactly what you need:

```ruby
module Types
  include Dry::Types()

  LocalizedText = Hash.schema(text: String, locale: String)
  LocalizedTextArray = Types.Array(LocalizedText)
end

class X < Dry::Struct
  attribute :name, Types::LocalizedTextArray
end
```

```
[1] pry(main)> X.new(name: nil)
Dry::Struct::Error: [X.new] nil (NilClass) has invalid type for :name violates constraints (type?(Array, nil) failed)
[2] pry(main)> X.new(name: {})
Dry::Struct::Error: [X.new] {} (Hash) has invalid type for :name violates constraints (type?(Array, {}) failed)
[3] pry(main)> X.new(name: [{text: 1, locale: 1}])
Dry::Struct::Error: [X.new] [{:text=>1, :locale=>1}] (Array) has invalid type for :name violates constraints (1 (Integer) has invalid type for :text violates constraints (type?(String, 1) failed) failed)
from /Users/gordon/.rvm/gems/ruby-2.5.5@dry-types/bundler/gems/dry-struct-eb005ade4f6e/lib/dry/struct/class_interface.rb:234:in `rescue in new'
```

I'm working on a new release atm, this is going to be 1.0. Expect it pushed in a few days or even sooner.

**Comment by twe4ked** [comment]
Great! Thanks for the update.
