### ISSUE TITLE
getting no method error

### ISSUE THREAD

**Issue by djaircarvalho** [dry-rb/dry-types#322]
I'm getting this error when running my rspec suit. but this error does not occur when running just this single test.
Failure/Error: attribute :produto, Produto
``` ssh
     
     NoMethodError:
       undefined method `meta' for #<Class:0x000055958d1fbc10>
     # /home/djair/.rvm/gems/ruby-2.5.0@api/gems/dry-types-1.0.0/lib/dry/types/schema/key.rb:29:in `block in initialize'
     # /home/djair/.rvm/gems/ruby-2.5.0@api/gems/dry-core-0.4.7/lib/dry/core/constants.rb:58:in `default'
     # /home/djair/.rvm/gems/ruby-2.5.0@api/gems/dry-types-1.0.0/lib/dry/types/schema/key.rb:28:in `initialize'
     # /home/djair/.rvm/gems/ruby-2.5.0@api/gems/dry-types-1.0.0/lib/dry/types/hash.rb:118:in `new'
     # /home/djair/.rvm/gems/ruby-2.5.0@api/gems/dry-types-1.0.0/lib/dry/types/hash.rb:118:in `block in build_keys'
     # /home/djair/.rvm/gems/ruby-2.5.0@api/gems/dry-types-1.0.0/lib/dry/types/hash.rb:116:in `each'
     # /home/djair/.rvm/gems/ruby-2.5.0@api/gems/dry-types-1.0.0/lib/dry/types/hash.rb:116:in `map'
     # /home/djair/.rvm/gems/ruby-2.5.0@api/gems/dry-types-1.0.0/lib/dry/types/hash.rb:116:in `build_keys'
     # /home/djair/.rvm/gems/ruby-2.5.0@api/gems/dry-types-1.0.0/lib/dry/types/schema.rb:225:in `schema'
     # /home/djair/.rvm/gems/ruby-2.5.0@api/gems/dry-types-1.0.0/lib/dry/types/constructor.rb:185:in `method_missing'
     # /home/djair/.rvm/gems/ruby-2.5.0@api/gems/dry-struct-1.0.0/lib/dry/struct/class_interface.rb:155:in `attributes'
     # /home/djair/.rvm/gems/ruby-2.5.0@api/gems/dry-struct-1.0.0/lib/dry/struct/class_interface.rb:100:in `attribute'
     # ./app/wrappers/comerciantes/entities/cupom.rb:17:in `<class:Cupom>'
     # ./app/wrappers/comerciantes/entities/cupom.rb:5:in `<module:Entities>'
     # ./app/wrappers/comerciantes/entities/cupom.rb:4:in `<module:Comerciantes>'
     # ./app/wrappers/comerciantes/entities/cupom.rb:3:in `<top (required)>'
     # ./app/wrappers/comerciantes_wrapper.rb:32:in `block in parsear_cupons'
     # ./app/wrappers/comerciantes_wrapper.rb:32:in `map'
     # ./app/wrappers/comerciantes_wrapper.rb:32:in `parsear_cupons'
     # ./app/wrappers/comerciantes_wrapper.rb:19:in `block in cupons'
     # /home/djair/.rvm/gems/ruby-2.5.0@api/gems/httparty-0.16.3/lib/httparty/response.rb:43:in `tap'
     # ./app/wrappers/comerciantes_wrapper.rb:16:in `cupons'
     # ./spec/wrappers/comerciantes_wrapper_spec.rb:30:in `block (3 levels) in <top (required)>'

```

**Comment by augustocbx** [comment]
How did you solved this issue?

**Comment by flash-gordon** [comment]
@augustocbx please provide a reproducible example and post a question at https://discourse.dry-rb.org/

**Comment by djaircarvalho** [comment]
I didn't remember but I think it was something related to a class with the same name in the main ruby project.
