### ISSUE TITLE
Invalid handling of Dry::Struct named like one of the Dry::Types

### ISSUE THREAD

**Issue by mfly** [dry-rb/dry-types#340]
While working on adding support for the newest dry-struct to https://github.com/quicktype/quicktype I came across a strange bug.
Some of the test cases in this project declare structs with names the same as types in `dry-types` eg. `Bool`, `Integer` etc. and use them as attribute types in other structs.
This should not be a problem since these types are included in a separate module but attribute types seem to resolved to `dry-type` built in types instead of the custom ones.
Here's an example:

```
require 'dry-struct'

module Types
  include Dry.Types
end

class Bool < Dry::Struct
  attribute :count, ::Types::Integer
end

bool_instance = ::Bool.new(count: 123)


class Container < Dry::Struct
  attribute :bool, ::Bool
end

pp Container.schema
Container.new(bool: bool_instance)
```

output:
```
#<Dry::Types[Constructor<Schema<keys={bool: Sum<Constrained<Nominal<TrueClass> rule=[type?(TrueClass)]> | Constrained<Nominal<FalseClass> rule=[type?(FalseClass)]>>}> fn=Kernel.Hash>]>
Traceback (most recent call last):
	2: from test.rb:20:in `<main>'
	1: from (...)/vendor/bundle/ruby/2.5.0/gems/dry-struct-1.0.0/lib/dry/struct/class_interface.rb:225:in `new'
(...)/vendor/bundle/ruby/2.5.0/gems/dry-struct-1.0.0/lib/dry/struct/class_interface.rb:234:in `rescue in new': [Container.new] #<Bool count=123> (Bool) has invalid type for :bool violates constraints (type?(FalseClass, #<Bool count=123>) failed) (Dry::Struct::Error)
```

**Comment by flash-gordon** [comment]
yeah, I already determined the root cause, will fix it and push a new version today

**Comment by mfly** [comment]
Awesome, thanks!
