### ISSUE TITLE
Hash Schema should normal Types DSL for `optional` keys

### ISSUE THREAD

**Issue by dsennerlov** [dry-rb/dry-types#352]
### Description
For consistency `Dry::Types.Hash.schema` should use `optional` for optional keys but require `.meta(omittable: true)` right now.

### Reproduce
```ruby
SimpleHash = Types::Hash.schema(
	meta_omittable_key: Types::String.meta(omittable: true), 
	optional_key: Types::String.optional
)

SimpleHash[{}] # => :optional_key is missing in Hash input (Dry::Types::MissingKeyError)
SimpleHash[{ optional_key: "value" }] # => No exception
```

### Stacktrace
```
Traceback (most recent call last):
        7: from dry_types_test.rb:49:in `<main>'
        6: from /home/vagrant/.bundler/ruby/2.5.0/gems/dry-types-1.1.1/lib/dry/types/type.rb:49:in `call'
        5: from /home/vagrant/.bundler/ruby/2.5.0/gems/dry-types-1.1.1/lib/dry/types/constructor.rb:86:in `call_unsafe'
        4: from /home/vagrant/.bundler/ruby/2.5.0/gems/dry-types-1.1.1/lib/dry/types/schema.rb:62:in `call_unsafe'
        3: from /home/vagrant/.bundler/ruby/2.5.0/gems/dry-types-1.1.1/lib/dry/types/schema.rb:326:in `resolve_unsafe'
        2: from /home/vagrant/.bundler/ruby/2.5.0/gems/dry-types-1.1.1/lib/dry/types/schema.rb:362:in `resolve_missing_keys'
        1: from /home/vagrant/.bundler/ruby/2.5.0/gems/dry-types-1.1.1/lib/dry/types/schema.rb:362:in `each'
/home/vagrant/.bundler/ruby/2.5.0/gems/dry-types-1.1.1/lib/dry/types/schema.rb:371:in `block in resolve_missing_keys': :optional_key is missing in Hash
input (Dry::Types::MissingKeyError)
```

### Gemfile.lock

```
    dry-types (1.1.1)
      concurrent-ruby (~> 1.0)
      dry-container (~> 0.3)
      dry-core (~> 0.4, >= 0.4.4)
      dry-equalizer (~> 0.2, >= 0.2.2)
      dry-inflector (~> 0.1, >= 0.1.2)
      dry-logic (~> 1.0, >= 1.0.2)
```

### Note

As a related side note, Hash.schema does not inherit optional prop from defined Types:

```ruby
OptionalString = Types::Coercible::String.optional

SimpleHash = Types::Hash.schema(key: OptionalString)
SimpleHash[{}] # => :key is missing in Hash input (Dry::Types::MissingKeyError)
```

**Comment by flash-gordon** [comment]
This is not a bug.
Optional means the value can be `nil`. This doesn't affect whether the key is required/omittable or not. To make a key in a schema optional, you can also use question-marked attributes:

```ruby
Types::Hash.schema(omittable_key?: Types::String, another_omittable_key?: Types::String.optional)
```
