### ISSUE TITLE
Can't boot with ruby 3.3.0 and dry-configurable

### ISSUE THREAD

**Issue by brauliobo** [dry-rb/dry-types#476]
On my application boot, it is crashing on trying to register the first `String` nominal type I get the following with ruby 3.3.0.

Same issue https://discourse.dry-rb.org/t/ruby-upgrade-causing-dry-container-failuers/1798

```ruby
/srv/media-downloader-bot/vendor/bundle/ruby/3.3.0/gems/dry-core-1.0.1/lib/dry/core/container/mixin.rb:114:in `register': undefined method `call' for an instance of Hash (NoMethodError)

          config.registry.call(_container, key, item, options)
                         ^^^^^
        from /srv/media-downloader-bot/vendor/bundle/ruby/3.3.0/gems/dry-types-1.7.2/lib/dry/types.rb:105:in `register'
        from /srv/media-downloader-bot/vendor/bundle/ruby/3.3.0/gems/dry-types-1.7.2/lib/dry/types/core.rb:51:in `block in <module:Types>'
        from /srv/media-downloader-bot/vendor/bundle/ruby/3.3.0/gems/dry-types-1.7.2/lib/dry/types/core.rb:47:in `each'
        from /srv/media-downloader-bot/vendor/bundle/ruby/3.3.0/gems/dry-types-1.7.2/lib/dry/types/core.rb:47:in `<module:Types>'
        from /srv/media-downloader-bot/vendor/bundle/ruby/3.3.0/gems/dry-types-1.7.2/lib/dry/types/core.rb:4:in `<module:Dry>'
        from /srv/media-downloader-bot/vendor/bundle/ruby/3.3.0/gems/dry-types-1.7.2/lib/dry/types/core.rb:3:in `<top (required)>'
        from /home/braulio/.rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
        from /home/braulio/.rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
        from /srv/media-downloader-bot/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.7.0/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
        from /srv/media-downloader-bot/vendor/bundle/ruby/3.3.0/gems/dry-types-1.7.2/lib/dry/types.rb:258:in `<top (required)>'
        from /home/braulio/.rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
        from /home/braulio/.rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
        from /srv/media-downloader-bot/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.7.0/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
        from /srv/media-downloader-bot/vendor/bundle/ruby/3.3.0/gems/dry-struct-1.6.0/lib/dry/struct.rb:6:in `<top (required)>'
        from /home/braulio/.rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
        from /home/braulio/.rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
        from /srv/media-downloader-bot/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.7.0/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
        from /srv/media-downloader-bot/vendor/bundle/ruby/3.3.0/gems/dry-struct-1.6.0/lib/dry-struct.rb:3:in `<top (required)>'
        from /home/braulio/.rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
        from /home/braulio/.rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
        from /srv/media-downloader-bot/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.7.0/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
        from /srv/media-downloader-bot/vendor/bundle/ruby/3.3.0/bundler/gems/telegram-bot-ruby-abd0c60322d4/lib/telegram/bot.rb:8:in `<top (required)>'
        from /home/braulio/.rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
        from /home/braulio/.rvm/rubies/ruby-3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
        from /srv/media-downloader-bot/lib/bot.rb:3:in `<top (required)>'
        from bin/auto:3:in `require_relative'
        from bin/auto:3:in `<main>'
```

`dry-types` was already in repo without errors.

By adding `dry-configurable` with `tdlib-ruby` then I get this error:

```diff
braulio @ bhavapower ➜  media-downloader-bot git:(main) ✗  g d Gemfile.lock 
diff --git a/Gemfile.lock b/Gemfile.lock
index d198888..2b507f0 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -36,6 +36,8 @@ GEM
     domain_name (0.6.20240107)
     dotenv (3.1.4)
     drb (2.2.1)
+    dry-configurable (0.7.0)
+      concurrent-ruby (~> 1.0)
     dry-core (1.0.1)
       concurrent-ruby (~> 1.0)
       zeitwerk (~> 2.6)
@@ -123,6 +125,9 @@ GEM
     sequel (5.85.0)
       bigdecimal
     srt (0.1.5)
+    tdlib-ruby (1.0.0)
+      concurrent-ruby (~> 1.0)
+      dry-configurable (~> 0.7)
     tzinfo (2.0.6)
       concurrent-ruby (~> 1.0)
     uri (0.13.1)
@@ -152,6 +157,7 @@ DEPENDENCIES
   roda
   sequel
   srt
+  tdlib-ruby
   telegram-bot-ruby!
   whisper.cpp
```

**Comment by brauliobo** [comment]
Relaxing the `dry-configurable` to update made it work, related to https://github.com/southbridgeio/tdlib-ruby/pull/70
