### ISSUE TITLE
Dry::Types::Struct should be allowed to be blank

### ISSUE THREAD

**Issue by joevandyk** [dry-rb/dry-types#56]
https://github.com/joevandyk/dry-types/commit/84979b0534d2e9d420e96ba6f73898261de073db has the failing test.

Test output:
```
Failures:

  1) Dry::Types::Struct.attribute works on blank structs
     Failure/Error: super(constructor[attributes])

     NoMethodError:
       undefined method `[]' for nil:NilClass
     # ./lib/dry/types/struct.rb:48:in `new'
     # ./spec/dry/types/struct_spec.rb:97:in `block (3 levels) in <top (required)>'
 

Finished in 0.09924 seconds (files took 0.92103 seconds to load)
173 examples, 1 failure
```

**Comment by backus** [comment]
I believe this was closed by https://github.com/dry-rb/dry-types/commit/cd98b2d99432c6cc20e3c71fe49c837499c0cb74
